// gfxmap.h
// Resolves sprite names to C2D images at runtime. Every asset directory
// holds a gfx.t3x spritesheet and the gfx.h header generated by tex3ds;
// this module parses the "#define gfx_<name>_idx <n>" lines of that header
// into a name -> index table stored next to the spritesheet, so each loaded
// GfxAssets resolves its own names independently of later loads.
#pragma once

#include <citro2d.h>
#include <stdbool.h>

#define GFX_NAME_MAX  96

// One "#define <name> <index>" entry of a tex3ds header.
typedef struct {
	char name[GFX_NAME_MAX];  // full macro name, e.g. "gfx_background_idx"
	int index;                // image index in the spritesheet
} GfxImageIndex;

// A spritesheet and the name -> index table of its tex3ds header. A zeroed
// GfxAssets is the "not loaded" state; free it with gfxmap_free_assets().
typedef struct {
	C2D_SpriteSheet sheet;
	GfxImageIndex *indexes;   // owned, count entries
	size_t count;
} GfxAssets;

// Image `name` (the PNG basename, e.g. "background", without the gfx_
// prefix or _idx suffix) from `assets`. Returns an empty image
// (tex == NULL) and prints a warning if the name is unknown.
C2D_Image gfxmap_get_image(const GfxAssets *assets, const char *name);
// Load <path>/gfx.t3x and its <path>/gfx.h index table into *assets.
// On failure returns false and leaves *assets zeroed. The caller owns the
// result and releases it with gfxmap_free_assets().
bool gfxmap_load_assets(const char *path, GfxAssets *assets);
// Free the spritesheet and index table of *assets and zero it, so a second
// call (or a call on a never-loaded GfxAssets) is harmless. Images obtained
// from it become invalid.
void gfxmap_free_assets(GfxAssets *assets);
// Converts a color name used in the HUD and timeline files (RED, BLUE, GREEN,
// YELLOW, BLACK, WHITE) to a C2D color. WHITE is a light grey; unknown names
// silently fall back to the same light grey.
u32 gfxmap_parse_color(const char *name);
