// gfxmap.h
// Resolves sprite names to C2D images at runtime. Every asset directory
// holds a gfx.t3x spritesheet and the gfx.h header generated by tex3ds;
// this module parses the "#define gfx_<name>_idx <n>" lines of that header
// into a single global name -> index table.
// Pitfall: the table is shared and reset by each gfxmap_load(), so look up
// images right after loading their header, before any other load.
#pragma once

#include <citro2d.h>
#include <stdbool.h>

#define GFX_NAME_MAX  96

// One "#define <name> <index>" entry of a tex3ds header.
typedef struct {
    char name[GFX_NAME_MAX];  // full macro name, e.g. "gfx_background_idx"
    int index;                // image index in the spritesheet
} GfxImageIndex;

// Index of image `name` (the PNG basename, e.g. "background", without the
// gfx_ prefix or _idx suffix) in the last loaded header, or -1 if unknown.
int gfxmap_get_index(const char *name);
// Image `name` from `assets`, using the last loaded header. Returns an empty
// image (tex == NULL) and prints a warning if the name is unknown.
C2D_Image gfxmap_get_image(C2D_SpriteSheet assets, const char *name);
// Replace the global table with the indexes declared in tex3ds header
// `filename`. Returns false if the file can't be opened or has too many
// images.
bool gfxmap_load(const char *filename);
// Load <path>/gfx.t3x into *assets and its <path>/gfx.h index table.
// On failure returns false and leaves *assets NULL. The caller owns the
// spritesheet and frees it with C2D_SpriteSheetFree().
bool gfxmap_load_assets(const char *path, C2D_SpriteSheet *assets);
// Converts a color name used in the HUD and timeline files (RED, BLUE, GREEN,
// YELLOW, BLACK, WHITE) to a C2D color. WHITE is a light grey; unknown names
// silently fall back to the same light grey.
u32 gfxmap_parse_color(const char *name);
